version: '3.2'

services:
  nodered:
    image: ghcr.io/uniba-ktr/iotrtc-nodered
    restart: unless-stopped
    container_name: nodered
    privileged: true
    build:
      context: ./nodered
      dockerfile: Dockerfile
    environment:
      - PUSH_HOST="10.42.0.1:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nodered-data:/data
    ports:
      - 1880:1880

volumes:
  nodered-data:
